# Generated by Django 2.2.1 on 2019-09-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='本のタイトル')),
                ('author', models.CharField(max_length=20, verbose_name='筆者の名前')),
                ('image', models.ImageField(upload_to='', verbose_name='表紙')),
                ('register_day', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
            ],
        ),
        migrations.CreateModel(
            name='Likephrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(null=True, verbose_name='ページ数')),
                ('like_phrase', models.TextField(null=True, verbose_name='好きなフレーズ')),
                ('comment', models.TextField(null=True, verbose_name='コメント')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Book')),
            ],
        ),
    ]
